# *******************************************************************************************
# *******************************************************************************************
#
#       Name :      build.py
#       Purpose :   Create build file
#       Date :      11th April 2023
#       Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,re,sys

# *******************************************************************************************
#
#										Builder class
#
# *******************************************************************************************

class Builder(object):
	def __init__(self,searchDir = "."):
		self.incFiles = []
		self.asmFiles = []
		self.defFiles = []
		self.scanForFiles(searchDir)
	#
	#		Scan source the for required modules.
	#
	def scanForFiles(self,searchDir):
		for root,dirs,files in os.walk(searchDir+os.sep+"source"):
			for f in files:
				if not f.startswith("_"):
					if f.endswith(".inc"):
						self.incFiles.append(root+os.sep+f)
					if f.endswith(".def"):
						self.defFiles.append(root+os.sep+f)
					if f.endswith(".asm"):
						self.asmFiles.append(root+os.sep+f)			

		self.asmFiles.sort(key = lambda x:x.split(os.sep)[-1])
		self.incFiles.sort(key = lambda x:x.split(os.sep)[-1])

	def createFile(self):
		h = open("_library.asm","w")
		h.write(";\n;\tThis file is automatically generated\n;\n")
		for f in self.incFiles+self.asmFiles:
			for s in open(f).readlines():
				if s.strip().startswith("#include"):
					incFile = os.sep.join(f.split(os.sep)[:-1])+os.sep+(s.replace('"',"").strip()[8:].strip())
					for s2 in open(incFile).readlines():
						h.write(s2)
				else:
					h.write(s)				
		h.close()

	def getINCFiles(self):
		return self.incFiles
	def getASMFiles(self):
		return self.asmFiles
	def getDEFFiles(self):
		return self.defFiles
		
if __name__ == "__main__":
 	Builder().createFile()
