# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		pcodeconst.py
#		Purpose :	P-Code constants (from autogenerated file)
#		Date :		15th April 2023
#		Author : 	Paul Robson .paul@robsons.org.uk
#
# *******************************************************************************************
# *******************************************************************************************

import os,re,sys
from pcodeconstraw import *

# *******************************************************************************************
#
#									Get constant structure
#
# *******************************************************************************************

class PCodeConstants(object):
	def __init__(self):
		self.idToToken = {}
		self.tokenToID = {}
		for e in PCodeConstantsRaw().get().split("|"):
			e = e.split(":")
			n = int(e[0])
			t = e[1].strip().lower()
			self.idToToken[n] = t
			self.tokenToID[t] = n

	def getToken(self,i):
		return self.idToToken[i] if i in self.idToToken else None
		
	def getID(self,t):
		t = t.strip().lower()
		return self.tokenToID[t] if t in self.tokenToID else None


if __name__ == "__main__":
	pc = PCodeConstants()
	print(pc.idToToken)
	print(pc.tokenToID)

