; *******************************************************************************************
; *******************************************************************************************
;
;		Name : 		tokens.inc
;		Purpose :	C64 Token constants.
;		Date :		11th April 2023
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; *******************************************************************************************
; *******************************************************************************************

C64_END = 128
C64_FOR = 129
C64_NEXT = 130
C64_DATA = 131
C64_INPUT_HASH = 132
C64_INPUT = 133
C64_DIM = 134
C64_READ = 135
C64_LET = 136
C64_GOTO = 137
C64_RUN = 138
C64_IF = 139
C64_RESTORE = 140
C64_GOSUB = 141
C64_RETURN = 142
C64_REM = 143
C64_STOP = 144
C64_ON = 145
C64_WAIT = 146
C64_LOAD = 147
C64_SAVE = 148
C64_VERIFY = 149
C64_DEF = 150
C64_POKE = 151
C64_PRINT_HASH = 152
C64_PRINT = 153
C64_CONT = 154
C64_LIST = 155
C64_CLR = 156
C64_CMD = 157
C64_SYS = 158
C64_OPEN = 159
C64_CLOSE = 160
C64_GET = 161
C64_NEW = 162
C64_TAB_LB = 163
C64_TO = 164
C64_FN = 165
C64_SPC_LB = 166
C64_THEN = 167
C64_NOT = 168
C64_STEP = 169

C64_ADD  = 170
C64_SUBTRACT  = 171
C64_MULTIPLY  = 172
C64_DIVIDE  = 173
C64_POWER  = 174
C64_AND = 175
C64_OR = 176
C64_GREATER  = 177
C64_EQUAL  = 178
C64_LESS  = 179

C64_SGN = 180
C64_INT = 181
C64_ABS = 182
C64_USR = 183
C64_FRE = 184
C64_POS = 185
C64_SQR = 186
C64_RND = 187
C64_LOG = 188
C64_EXP = 189
C64_COS = 190
C64_SIN = 191
C64_TAN = 192
C64_ATN = 193
C64_PEEK = 194
C64_LEN = 195
C64_STR_S = 196
C64_VAL = 197
C64_ASC = 198
C64_CHR_S = 199
C64_LEFT_S = 200
C64_RIGHT_S = 201
C64_MID_S = 202

C64_GO = 203
