# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		tobinary.py
#		Purpose :	Convert file to binary
#		Date :		28th May 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys

f = sys.argv[1]
code = [x for x in open(f,"rb").read(-1)]
name = f.replace(".prg","").split(os.sep)[-1]
s = ",".join([str(x) for x in code])
h = open(sys.argv[2],"w")
h.write("// This file is automatically generated.\n")
h.write("#define {0}_SIZE {1}\n".format(name.upper(),len(code)))
h.write("static const BYTE8 {0}_code[] = {{ {1} }};\n\n".format(name,s))
h.close()