#
#	This file is automatically generated
#
class PCodeConstantsRaw(object):
	def get(self):
		return "128:+|129:-|130:*|131:/|132:^|133:and|134:or|135:>|136:=|137:<|138:>=|139:<>|140:<=|141:.shift|142:.byte|143:.word|144:.float|145:.string|146:.data|147:.goto|148:.gosub|149:.goto.z|150:.goto.nz|151:.varspace"
