# *******************************************************************************************
# *******************************************************************************************
#
#       Name :      build.py
#       Purpose :   Create build file
#       Date :      11th April 2023
#       Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,re,sys

# *******************************************************************************************
#
#										Builder class
#
# *******************************************************************************************

class Builder(object):
	def __init__(self):
		self.defines = []
		self.incFiles = []
		self.asmFiles = []
		self.defFiles = []
		self.target = [x[2:] for x in sys.argv if x.startswith("-o")][0]
		self.main = [x[2:] for x in sys.argv if x.startswith("-m")][0]
		self.scanForFiles()
	#
	#		Scan source the for required modules.
	#
	def scanForFiles(self):
		for root,dirs,files in os.walk("modules"):
			isOk = False
			parts = root.split(os.sep)
			if len(parts) >= 2:
				isOk = parts[1] in sys.argv or parts[1] == "common"
			if len(parts) == 2:
				self.defines.append("module_{0} = {1}".format(parts[-1].replace(".","_"),1 if isOk else 0))
				self.defines.append("ismain_{0} = {1}".format(parts[-1].replace(".","_"),1 if parts[-1] == self.main else 0))
			#print(root,isOk,files)
			if isOk:
				for f in files:
					if not f.startswith("_"):
						if f.endswith(".inc"):
							self.incFiles.append(root+os.sep+f)
						if f.endswith(".asm") and f != self.target :
							self.asmFiles.append(root+os.sep+f)			
						if f.endswith(".def"):
							self.defFiles.append(root+os.sep+f)

		self.asmFiles.sort(key = lambda x:x.split(os.sep)[-1])
		self.defFiles.sort(key = lambda x:x.split(os.sep)[-1])
		self.incFiles.sort(key = lambda x:x.split(os.sep)[-1])

	def createFile(self):
		h = open(self.target,"w")
		h.write(";\n;\tThis file is automatically generated\n;\n")
		h.write("\n".join(self.defines)+"\n\n")
		for f in self.incFiles+self.asmFiles:
			h.write("\t.include\t\"{0}\"\n".format(f))
		h.close()

	def getINCFiles(self):
		return self.incFiles
	def getASMFiles(self):
		return self.asmFiles
	def getDEFFiles(self):
		return self.defFiles

if __name__ == "__main__":
 	Builder().createFile()
