# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		pcode.py
#		Purpose :	Runtime P-Code definition
#		Date :		12th April 2023
#		Author : 	Paul Robson .paul@robsons.org.uk
#
# *******************************************************************************************
# *******************************************************************************************

import os,re,sys
from c64tokens import *
from build import *

class PCode(object):
	def __init__(self,tokenList = [C64TokenStore()]):
		self.tokenList = tokenList
		self.currentID = 0x80
		self.defines = []
		self.idToToken = {}
		self.tokenToID = {}
		self.doBinaryUnary(tokenList)
		self.doCommands()
		self.doExtras()

	def doCommands(self):
		self.define("PCD_STARTCOMMAND")		
		for f in Builder().getASMFiles():
			for s in open(f).readlines():
				if s.find(";;") >= 0:
					m = re.match("^(.*?)\\:\\s*\\;\\;\\s*\\[(.*)\\]\\s*$",s)
					assert m is not None,"Bad line "+s
					if m.group(2)[0] != ".":
						self.token(m.group(2))
		self.define("PCD_ENDCOMMAND")		

	def doExtras(self):
		self.commandSize = {}
		self.startCommands = self.currentID
		self.define("PCD_STARTSYSTEM")		
		self.extra(".shift",1)
		self.extra(".byte",1)
		self.extra(".word",2)
		self.extra(".float",0xFF)
		self.extra(".string",0xFF)
		self.extra(".data",0xFF)
		self.extra(".goto",3)
		self.extra(".gosub",3)
		self.define("PCD_ENDSYSTEM")		

	def doBinaryUnary(self,tokenList):
		self.define("PCD_STARTBINARY")		
		self.addTokens(tokenList[0].getBinary()+",>=,<>,<=")
		self.define("PCD_ENDBINARY")		
		self.define("PCD_STARTUNARY")		
		for t in tokenList:
			self.addTokens(t.getUnary())
		self.define("PCD_ENDUNARY")		

	def addTokens(self,csList):
		for w in csList.split(","):
			self.token(w)

	def extra(self,cmd,size):
		self.commandSize[self.currentID] = size
		self.token(cmd)

	def define(self,name,pos = None):
		pos = self.currentID if pos is None else pos
		#print(name,pos)
		self.defines.append([name,pos])

	def token(self,name):
		name = name.strip().lower()
		if name not in self.tokenToID:
			self.tokenToID[name] = self.currentID
			self.idToToken[self.currentID] = name
			#print(self.currentID,name)	
			self.currentID += 1

	def dump(self):
		print(";\n;\tThis file is automatically generated\n;")
		for d in self.defines:
			print("{0} = ${1:02x}".format(d[0],d[1]))
		print()
		for i in range(0x80,self.currentID):
			s = self.tokenList[0].tidy(self.idToToken[i])
			print("{0:16} = ${1:02x} ; {2}".format("PCD_"+s.upper().replace(".","CMD_"),i,self.idToToken[i].lower()))

	def dumpSizeTable(self,f):
		h = open(f,"w")
		h.write(";\n;\tThis file is automatically generated\n;\n")
		for i in range(self.startCommands,self.currentID):
			h.write("\t.byte\t{0:<10}\t; ${1:02x} {2}\n".format(self.commandSize[i],i,self.idToToken[i].lower()))
		h.close()

if __name__ == "__main__":
	pc = PCode()
	pc.dump()
	pc.dumpSizeTable("modules/common/generated/pcodesize.dat")

# ***********************************************************************************************************************************************
#
#		0-63 			0-63	Constants 0-63, pushed on stack
# 		64-71 ll  		nn%@	Loads the 12 bit value .lower 3 bits of opcode, 11 bits of second byte, shifted left once as a 16 bit integer
# 		72-79 ll  		nn%!	Saves the 12 bit value .lower 3 bits of opcode, 11 bits of second byte, shifted left once as a 16 bit integer
#		80-87 ll 		nn@		As above but for a 32 bit ifloat
# 		88-95 ll 		nn! 	As above but for a 32 bit ifloat
# 		96-103 ll 		nn$@	As above but for a 16 bit string address
# 		104-111 ll 		nn$!	As above but for a 16 bit string address
# 		112-127 		.not used
#		128+ 			Binary operators in the same order as in the C64, ending with the aditional >= <> <= tokens
#		+ 				Unary operators
#		+ 				Command words
#		+				Data words ; these have associated data, the size of which is in a table
#
#							.SHIFT nn   		1		Shifted action word
#							.BYTE nn 			1 		Load unsigned int
#							.WORD ll hh 		2 		Load 16 bit integer
#							.FLOAT ll ss 		$FF		Float as string .$FF => length in first byte
#							.STRING ll ss 		$FF		ASCIIZ string
#							.DATA ll ss 		$FF		Packed data statements
#							.GOTO pp ll hh		3 		Go to page .0=default / offset from the current page beginning.
#							.GOSUB pp ll hh 	3 		Same but GOSUB
#
# ***********************************************************************************************************************************************

