#
#	This file is automatically generated
#
class PCodeConstantsRaw(object):
	def get(self):
		return "128:+|129:-|130:*|131:/|132:^|133:and|134:or|135:>|136:=|137:<|138:>=|139:<>|140:<=|141:sgn|142:int|143:abs|144:usr|145:fre|146:pos|147:sqr|148:rnd|149:log|150:exp|151:cos|152:sin|153:tan|154:atn|155:peek|156:len|157:str$|158:val|159:asc|160:chr$|161:left$|162:right$|163:mid$|164:assert|165:bin$|166:print.chr|167:clr|168:s.cmp|169:end|170:exit|171:debug|172:for|173:get|174:return|175:hex$|176:f.cmp|177:int.div|178:negate|179:new.line|180:next|181:not|182:poke|183:print.n|184:print.s|185:concat|186:print.tab|187:print.pos|188:print.spc|189:stop|190:sys|191:ti|192:wait|193:.shift|194:.byte|195:.word|196:.float|197:.string|198:.data|199:.goto|200:.gosub|201:.goto.z|202:.goto.nz"
