#
#	This file is automatically generated
#
class PCodeConstantsRaw(object):
	def get(self):
		return "128:+|129:-|130:*|131:/|132:^|133:and|134:or|135:>|136:=|137:<|138:>=|139:<>|140:<=|141:abs|142:array|143:asc|144:assert|145:bin$|146:print.chr|147:chr$|148:s.cmp|149:exit|150:debug|151:for|152:fre|153:get|154:return|155:hex$|156:len|157:f.cmp|158:int.div|159:negate|160:new.line|161:next|162:not|163:on|164:moreon|165:peek|166:poke|167:pos|168:getchannel|169:setchannel|170:print.n|171:print.s|172:read|173:read$|174:rnd|175:concat|176:sgn|177:print.tab|178:print.pos|179:print.spc|180:str$|181:left$|182:right$|183:mid$|184:ti|185:usr|186:val|187:.shift|188:.byte|189:.word|190:.float|191:.string|192:.data|193:.goto|194:.gosub|195:.goto.z|196:.goto.nz|197:.varspace|48000:clr|48001:dim|48002:end|48003:int|48004:sqr|48005:log|48006:exp|48007:cos|48008:sin|48009:tan|48010:atn|48011:restore|48012:stop|48013:sys|48014:wait"
