#
#	This file is automatically generated
#
class PCodeConstantsRaw(object):
	def get(self):
		return "128:+|129:-|130:*|131:/|132:^|133:and|134:or|135:>|136:=|137:<|138:>=|139:<>|140:<=|141:abs|142:array|143:asc|144:assert|145:bin$|146:print.chr|147:chr$|148:s.cmp|149:for|150:fre|151:get|152:return|153:hex$|154:input|155:input$|156:input.start|157:len|158:f.cmp|159:int.div|160:negate|161:new.line|162:next|163:not|164:on|165:moreon|166:peek|167:poke|168:pos|169:getchannel|170:setchannel|171:print.n|172:print.s|173:read|174:read$|175:rnd|176:concat|177:sgn|178:print.tab|179:print.pos|180:print.spc|181:str$|182:left$|183:right$|184:mid$|185:swap|186:ti|187:ti$|188:usr|189:val|190:close|191:exit|192:debug|193:open|194:vpoke|195:.shift|196:.byte|197:.word|198:.float|199:.string|200:.data|201:.goto|202:.gosub|203:.goto.z|204:.goto.nz|205:.varspace|50048:clr|50049:dim|50050:end|50051:int|50052:sqr|50053:log|50054:exp|50055:cos|50056:sin|50057:tan|50058:atn|50059:restore|50060:stop|50061:sys|50062:wait"
