# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		vectors.py
#		Purpose :	Generate vector table
#		Date :		12th April 2023
#		Author : 	Paul Robson .paul@robsons.org.uk
#
# *******************************************************************************************
# *******************************************************************************************

import os,re,sys
from pcode import *
from build import * 

vectors = {}
for f in Builder().getASMFiles():
	for s in open(f).readlines():
		if s.find(";;") >= 0:
			m = re.match("^(.*?)\\:\\s*\\;\\;\\s*\\[(.*)\\]\\s*$",s)
			assert m is not None,"Bad line "+s
			v = m.group(2).lower() 
			vectors[v[1:] if v.startswith("!") else v] = m.group(1)

pcodes = PCode().idToToken
ids = [x for x in pcodes.keys()]		
ids.sort()

print(";\n;\tThis file is automatically generated\n;")
print("\t.section code")
print("VectorTable:")
for i in ids:
	p = pcodes[i]
	if i > 256 and (i & 0xFF) == 0x80:
		print("\n\nShiftVectorTable:")
	s = vectors[p] if p in vectors else "Unimplemented"
	print("\t.word\t{0:24} ; ${1:02x} {2}".format(s,i,p.lower()))
print("\t.send code")
