;
;	This file is automatically generated
;
module_x16_hardware = 1
ismain_x16_hardware = 0
module_x16_runtime = 0
ismain_x16_runtime = 0
module_runtime = 0
ismain_runtime = 0
module_x16_compiler = 1
ismain_x16_compiler = 0
module_ifloat32 = 0
ismain_ifloat32 = 0
module_common = 1
ismain_common = 0
module_compiler = 1
ismain_compiler = 1
module_polynomials = 0
ismain_polynomials = 0

	.include	"modules/common/generated/c64tokens.inc"
	.include	"modules/common/data/common.inc"
	.include	"modules/compiler/config.inc"
	.include	"modules/common/data/data.inc"
	.include	"modules/compiler/aa.runtime/data.inc"
	.include	"modules/common/generated/errors.inc"
	.include	"modules/x16_hardware/config/machinecode.inc"
	.include	"modules/common/boot.end/macros.inc"
	.include	"modules/common/generated/pcodetokens.inc"
	.include	"modules/compiler/storage/storage.inc"
	.include	"modules/common/data/system.inc"
	.include	"modules/common/boot.end/00start.asm"
	.include	"modules/common/generated/errors.asm"
	.include	"modules/compiler/source/simple/get.asm"
	.include	"modules/x16_hardware/interface/getxpos.asm"
	.include	"modules/compiler/source/simple/line.asm"
	.include	"modules/compiler/storage/line.asm"
	.include	"modules/x16_hardware/interface/printchar.asm"
	.include	"modules/compiler/source/simple/reset.asm"
	.include	"modules/compiler/storage/reset.asm"
	.include	"modules/compiler/aa.runtime/runtime.asm"
	.include	"modules/x16_hardware/interface/save.asm"
	.include	"modules/common/boot.end/zzEnd.asm"
