;
;	This file is automatically generated
;
module_x16_hardware = 1
ismain_x16_hardware = 0
module_x16_runtime = 0
ismain_x16_runtime = 0
module_runtime = 0
ismain_runtime = 0
module_x16_compiler = 0
ismain_x16_compiler = 0
module_ifloat32 = 1
ismain_ifloat32 = 1
module_common = 1
ismain_common = 0
module_compiler = 0
ismain_compiler = 0
module_polynomials = 1
ismain_polynomials = 0

	.include	"modules/common/generated/c64tokens.inc"
	.include	"modules/common/data/common.inc"
	.include	"modules/polynomials/utility/constant.inc"
	.include	"modules/common/data/data.inc"
	.include	"modules/common/generated/errors.inc"
	.include	"modules/x16_hardware/config/machinecode.inc"
	.include	"modules/common/boot.end/macros.inc"
	.include	"modules/common/generated/pcodetokens.inc"
	.include	"modules/ifloat32/aa.testing/testing.inc"
	.include	"modules/common/boot.end/00start.asm"
	.include	"modules/ifloat32/float/addsub.asm"
	.include	"modules/polynomials/unary/atn.asm"
	.include	"modules/polynomials/core/atn_core.asm"
	.include	"modules/polynomials/generated/coefficients.asm"
	.include	"modules/ifloat32/float/compare.asm"
	.include	"modules/ifloat32/generated/constants.asm"
	.include	"modules/polynomials/generated/constants.asm"
	.include	"modules/polynomials/unary/cos.asm"
	.include	"modules/ifloat32/binary/divide.asm"
	.include	"modules/ifloat32/float/divide.asm"
	.include	"modules/common/generated/errors.asm"
	.include	"modules/polynomials/unary/exp.asm"
	.include	"modules/polynomials/core/exp_core.asm"
	.include	"modules/ifloat32/float/fractional.asm"
	.include	"modules/x16_hardware/interface/getxpos.asm"
	.include	"modules/polynomials/utility/horner.asm"
	.include	"modules/ifloat32/float/integer.asm"
	.include	"modules/ifloat32/float/integerdown.asm"
	.include	"modules/polynomials/utility/load.asm"
	.include	"modules/polynomials/unary/log.asm"
	.include	"modules/polynomials/core/log_core.asm"
	.include	"modules/ifloat32/binary/multiply.asm"
	.include	"modules/ifloat32/float/multiply.asm"
	.include	"modules/ifloat32/float/normalise.asm"
	.include	"modules/polynomials/unary/pi.asm"
	.include	"modules/polynomials/unary/power.asm"
	.include	"modules/x16_hardware/interface/printchar.asm"
	.include	"modules/x16_hardware/interface/save.asm"
	.include	"modules/ifloat32/binary/simple.asm"
	.include	"modules/polynomials/unary/sin.asm"
	.include	"modules/polynomials/core/sin_core.asm"
	.include	"modules/polynomials/unary/sqr.asm"
	.include	"modules/polynomials/unary/tan.asm"
	.include	"modules/ifloat32/aa.testing/testing.asm"
	.include	"modules/ifloat32/float/tofloat.asm"
	.include	"modules/ifloat32/binary/tostring.asm"
	.include	"modules/ifloat32/float/tostring.asm"
	.include	"modules/ifloat32/utility/utility.asm"
	.include	"modules/common/boot.end/zzEnd.asm"
