;
;	This file is automatically generated
;
module_runtime = 1
ismain_runtime = 1
module_ifloat32 = 1
ismain_ifloat32 = 0
module_common = 1
ismain_common = 0

	.include	"./modules/common/data/common.inc"
	.include	"./modules/runtime/config.inc"
	.include	"./modules/common/data/data.inc"
	.include	"./modules/common/boot.end/macros.inc"
	.include	"./modules/common/data/system.inc"
	.include	"./modules/common/boot.end/00start.asm"
	.include	"./modules/ifloat32/float/addsub.asm"
	.include	"./modules/ifloat32/float/compare.asm"
	.include	"./modules/ifloat32/generated/constants.asm"
	.include	"./modules/ifloat32/binary/divide.asm"
	.include	"./modules/ifloat32/float/divide.asm"
	.include	"./modules/ifloat32/float/fractional.asm"
	.include	"./modules/ifloat32/float/integer.asm"
	.include	"./modules/ifloat32/binary/multiply.asm"
	.include	"./modules/ifloat32/float/multiply.asm"
	.include	"./modules/ifloat32/float/normalise.asm"
	.include	"./modules/ifloat32/binary/simple.asm"
	.include	"./modules/ifloat32/float/tofloat.asm"
	.include	"./modules/ifloat32/binary/tostring.asm"
	.include	"./modules/ifloat32/float/tostring.asm"
	.include	"./modules/ifloat32/utility/utility.asm"
	.include	"./modules/common/boot.end/zzEnd.asm"
